backend:
  name: github
  repo: KiteRainCastle/KiteRainCastle.github.io  # 사용자님의 저장소 이름
  branch: main  # 저장소의 메인 브랜치 이름 (master 또는 main 확인)

publish_mode: editorial_workflow # 콘텐츠 워크플로우 활성화 (선택 사항)

media_folder: "images/uploads" # 이미지 파일을 저장할 폴더 (블로그 루트 기준)
public_folder: "/images/uploads"

collections:
  - name: "post"
    label: "블로그 포스트"
    folder: "_posts"
    create: true # 새 포스트 생성 허용
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # 포스트 파일 이름 형식
    fields:
      - {label: "레이아웃", name: "layout", widget: "hidden", default: "post"}
      - {label: "제목", name: "title", widget: "string", required: true}
      - {label: "작성 날짜", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss Z", format: "YYYY-MM-DD HH:mm:ss Z"}
      - {label: "카테고리", name: "categories", widget: "string"}
      - {label: "태그", name: "tags", widget: "list", required: false}
      - {label: "본문 내용", name: "body", widget: "markdown"}
